//
//  HeroPresenter.swift
//  HammerSystemsApp
//
//  Created by Zhoomartov Erbolot on 20.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol HeroPresentationLogic {
    func presentHeroModels(data: [HeroModel])
}

final class HeroPresenter {
    
    weak var viewController: HeroDisplayLogic?
    
}


// MARK: - HeroPresentationLogic
extension HeroPresenter: HeroPresentationLogic {
    
    func presentHeroModels(data: [HeroModel]) {
        viewController?.displayHeroModels(data)
    }
}


// MARK: - Private Zone
private extension HeroPresenter {
    
    
}
